---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app
  labels:
    run: spring-boot-app
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    run: spring-boot-app
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: spring-boot-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: spring-boot-app
    spec:
      containers:
      - name: spring-boot-app
        image: springio/spring-boot.app:1.0
        ports:
        - containerPort: 8080
